name:                sph
version:             0.1.0
github:              "schuermannator/sph"
license:             BSD3
author:              "Zach Schuermann"
maintainer:          "zachary.zvs@gmail.com"
copyright:           "2019 Zachary Schuermann"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/sph#readme>

dependencies:
- base >= 4.7 && < 5
- random
- linear
- GLUT
- deepseq
- parallel

library:
  source-dirs: src

executables:
  sph-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -O2
    - -threaded
    - -rtsopts
    - -eventlog
    #- -with-rtsopts=-N
    dependencies:
    - sph

tests:
  sph-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sph
